const data = [
  
    {
    id: "102",
    bezirk: "Mitte",
    bezeichnung: "50. Berliner Frühlingsfest auf dem Zentralen Festplatz",
    strasse: "Kurt-Schumacher-Damm 207",
    plz: "13405",
    von: "2022-03-23",
    bis: "2022-04-24",
    zeit: "Mi-Sa ab 14:00 So ab 1300",
    veranstalter: "Schaustellerverband Berlin e. V., Tel.: 213 32 90, Fax: 213 40 34",
    mail: "info@svbev.de",
    www: "http://www.volksfest-berlin.de",
    bemerkungen: "Mo, Di geschlossen, Ostern (So, Mo) ab 12:00, Karfreitag geschlossen, Eintritt frei, www.svbev.de",
    bild: "",
    copyright: "",
    rss_titel: "50. Berliner Frühlingsfest auf dem Zentralen Festplatz"
    },
    {
    id: "51",
    bezirk: "Charlottenburg-Wilmersdorf",
    bezeichnung: "Kunsthandwerkliches OSTERN am Karl-August-Platz",
    strasse: "Karl-August-Platz",
    plz: "10625",
    von: "2022-04-03",
    bis: "2022-04-03",
    zeit: "11:00-18:00",
    veranstalter: "Family & Friends e. V., Tel.: 305 55 21, Fax: 76 90 74 76",
    mail: "stadtkultur@family-and-friends-eV.de",
    www: "www.family-and-friends-eV.de",
    bemerkungen: "",
    bild: "",
    copyright: "",
    rss_titel: "Kunsthandwerkliches OSTERN am Karl-August-Platz"
    },
    {
    id: "156",
    bezirk: "Neukölln",
    bezeichnung: "Britzer Baumblüte",
    strasse: "Parchimer Allee",
    plz: "12359",
    von: "2022-04-08",
    bis: "2022-04-24",
    zeit: "14:00-22:00 So und Feiertage ab 12:00",
    veranstalter: "Schaustellerbetrieb Wollenschlaeger, Tel.: 03322/428 82 45, Fax: 03322/423 41 39, Mobil 0163/5000 600",
    mail: "info@wollenschlaeger-berlin.de",
    www: "www.wollenschlaeger-berlin.de",
    bemerkungen: "",
    bild: "",
    copyright: "",
    rss_titel: "Britzer Baumblüte"
    },
    {
    id: "54",
    bezirk: "Charlottenburg-Wilmersdorf",
    bezeichnung: "Kunsthandwerkliches OSTERN am Karl-August-Platz",
    strasse: "Karl-August-Platz",
    plz: "10625",
    von: "2022-04-10",
    bis: "2022-04-10",
    zeit: "11:00-18:00",
    veranstalter: "Family & Friends e. V., Tel.: 305 55 21, Fax: 76 90 74 76",
    mail: "stadtkultur@family-and-friends-eV.de",
    www: "www.family-and-friends-eV.de",
    bemerkungen: "",
    bild: "",
    copyright: "",
    rss_titel: "Kunsthandwerkliches OSTERN am Karl-August-Platz"
    },
    {
    id: "90",
    bezirk: "Steglitz-Zehlendorf",
    bezeichnung: "KUNST trifft HANDWERK",
    strasse: "Mexikoplatz",
    plz: "14163",
    von: "2022-04-10",
    bis: "2022-04-10",
    zeit: "11:00-18:00",
    veranstalter: "Cornelja Hasler, KUNSTHAND-BERLIN, Tel.: 40 63 70 31",
    mail: "info@kunsthand-berlin.de",
    www: "www.kunsthand-berlin.de",
    bemerkungen: "Kunsthandwerkermarkt, ca. 100 Aussteller, Handelsware nicht zugelassen, Vorplatz S-Bahnhof Mexikoplatz, Bülowstr. 1 - 8, Beerenstr. 66, Eintritt frei",
    bild: "",
    copyright: "",
    rss_titel: "KUNST trifft HANDWERK"
    },
    {
    id: "18",
    bezirk: "Spandau",
    bezeichnung: "14. Oster-Ritterfest auf der Zitadelle Spandau",
    strasse: "Am Juliusturm 64",
    plz: "13599",
    von: "2022-04-16",
    bis: "2022-04-18",
    zeit: "10:00-21:00",
    veranstalter: "Carnica Historische Feste & Märkte, Tel.: 0171/515 32 70, Fax: 033602/55 40 26",
    mail: "post@carnica.de",
    www: "www.carnica-spectaculi.de",
    bemerkungen: "Kinder bis 5 Jahre und Ritter in Vollrüstung frei, Erwachsene 12 €, Schüler, Studenten & Gewandete 9 €, Knder 6 - 16 Jahre 6 €, Familie 30 € (2 Erwachsene mit allen eigenen Kindern/Enkeln bis 16 Jahre)",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/ritterfest500.jpg",
    copyright: "Carnica",
    rss_titel: "14. Oster-Ritterfest auf der Zitadelle Spandau"
    },
    {
    id: "63",
    bezirk: "Tempelhof-Schöneberg",
    bezeichnung: "KUNST trifft WEIN",
    strasse: "Alt-Lichtenrade",
    plz: "12309",
    von: "2022-04-29",
    bis: "2022-05-01",
    zeit: "Fr-Sa 12:00-23:00 So 12:00-20:00",
    veranstalter: "Family & Friends e. V., Tel.: 305 55 21, Fax: 76 90 74 76",
    mail: "weinfest@family-and-friends-eV.de",
    www: "www.family-and-friends-eV.de",
    bemerkungen: "rund um den Dorfteich",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/ktw1.jpg",
    copyright: "André Ballin (Family & Friends e. V.)",
    rss_titel: "KUNST trifft WEIN"
    },
    {
    id: "159",
    bezirk: "Neukölln",
    bezeichnung: "Neuköllner Maientage",
    strasse: "Columbiadamm 160",
    plz: "10965",
    von: "2022-04-29",
    bis: "2022-05-22",
    zeit: "tgl ab 15:00 So und Feiertage ab 14:00",
    veranstalter: "Schaustellerbetrieb Wollenschlaeger, Tel.: 03322/428 82 45, Fax: 03322/423 41 39, Mobil 0163/5000 600",
    mail: "info@wollenschlaeger-berlin.de",
    www: "www.wollenschlaeger-berlin.de",
    bemerkungen: "Festplatz Staaken",
    bild: "",
    copyright: "",
    rss_titel: "Neuköllner Maientage"
    },
    {
    id: "174",
    bezirk: "Steglitz-Zehlendorf",
    bezeichnung: "Frühlingsfest auf der Domäne Dahlem",
    strasse: "Königin-Luise-Straße 49",
    plz: "14195",
    von: "2022-04-30",
    bis: "2022-05-01",
    zeit: "",
    veranstalter: "Domäne Dahlem Veranstaltungsgesellschaft mbH, Königin-Luise-Str. 49, 14195 Berlin, Tel.: 66 63 00 19, Fax: 66 63 00 20",
    mail: "marktfeste@domaene-dahlem.de",
    www: "https://www.domaene-dahlem.de/marktfeste/",
    bemerkungen: "Eintritt regulär 3,50 €, ermäßigt 2 €, Kinder unter 12 frei",
    bild: "",
    copyright: "",
    rss_titel: "Frühlingsfest auf der Domäne Dahlem"
    },
    {
    id: "261",
    bezirk: "Treptow-Köpenick",
    bezeichnung: "30. Fest auf der Bölschestraße in Berlin-Friedrichshagen",
    strasse: "Bölschestraße",
    plz: "12587",
    von: "2022-05-07",
    bis: "2022-05-08",
    zeit: "Sa 10:00-22:00 So 10:00-20:00",
    veranstalter: "Laubinger Event GmbH, Tel.: 033439 7714 34 90, Fax: 033439/14 34 92",
    mail: "info@laubinger.de",
    www: "www.laubinger.de",
    bemerkungen: "Traditionsreiches Straßenfest mit großem Bühnenprogramm, Trödel- und Kunstmarkt, Eintritt frei",
    bild: "",
    copyright: "",
    rss_titel: "30. Fest auf der Bölschestraße in Berlin-Friedrichshagen"
    },
    {
    id: "273",
    bezirk: "Tempelhof-Schöneberg",
    bezeichnung: "Primavera",
    strasse: "Akazienstraße",
    plz: "10823",
    von: "2022-05-07",
    bis: "2022-05-08",
    zeit: "Sa 11:00-21:00 So 10:00-20:00",
    veranstalter: "MS-Event-Agentur GmbH, Geschäftsführerin Frau Sieg-Heuke, Tel.: 0173/237 88 55",
    mail: "berlin@ms-event-agentur.com",
    www: "http://www.ms-event-agentur.com/",
    bemerkungen: "Akazien-/Belziger Straße, Eintritt frei",
    bild: "",
    copyright: "",
    rss_titel: "Primavera"
    },
    {
    id: "27",
    bezirk: "Neukölln",
    bezeichnung: "Rudower Frühlingsmeile",
    strasse: "Alt-Rudow",
    plz: "12357",
    von: "2022-05-07",
    bis: "2022-05-08",
    zeit: "Sa 12:00-22:00  So 11:00-20:00",
    veranstalter: "Jüttner Entertainment, Tel.: 88 70 80 81, 88 70 80 82, Fax: 66 70 30 03, Mobil 0152/33 90 83 98",
    mail: "info@juettner-entertainment.de",
    www: "www.juettner-entertainment.de",
    bemerkungen: "Alt-Rudow und Krokusstraße, Eintritt frei, Bühnenprogramm, Street Food, Kunsthandwerk, Kinderfahrgeschäfte",
    bild: "",
    copyright: "",
    rss_titel: "Rudower Frühlingsmeile"
    },
    {
    id: "57",
    bezirk: "Charlottenburg-Wilmersdorf",
    bezeichnung: "Frühlingszauber in Westend",
    strasse: "Preußenallee",
    plz: "14052",
    von: "2022-05-07",
    bis: "2022-05-08",
    zeit: "Sa 12:00-23:00 So 12:00-20:00",
    veranstalter: "Family & Friends e. V., Tel.: 305 55 21, Fax: 76 90 74 76",
    mail: "stadtkultur@family-and-friends-eV.de",
    www: "www.family-and-friends.de",
    bemerkungen: "",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/fruehlingszauberwestend.jpg",
    copyright: "André Ballin (Family & Friends e. V.)",
    rss_titel: "Frühlingszauber in Westend"
    },
    {
    id: "96",
    bezirk: "Reinickendorf",
    bezeichnung: "KUNST trifft HANDWERK Frohnau",
    strasse: "Zeltinger Platz",
    plz: "13465",
    von: "2022-05-07",
    bis: "2022-05-08",
    zeit: "11:00-18:00",
    veranstalter: "Cornelja Hasler, KUNSTHAND-BERLIN, Tel.: 40 63 70 31",
    mail: "info@kunsthand-berlin.de",
    www: "www.kunsthand-berlin.de",
    bemerkungen: "Kunsthandwerkermarkt, ca. 120 Aussteller, Handelsware nicht zugelassen, Zentrum der Gartenstadt Frohnau, Zeltinger Platz/Wiltinger Str. 1-26 oder Ludolfingerplatz, Eintritt frei",
    bild: "",
    copyright: "",
    rss_titel: "KUNST trifft HANDWERK Frohnau"
    },
    {
    id: "123",
    bezirk: "Treptow-Köpenick",
    bezeichnung: "Späth'er Frühling",
    strasse: "Späthstraße 80/81",
    plz: "12437",
    von: "2022-05-07",
    bis: "2022-05-08",
    zeit: "09:00-18:00",
    veranstalter: "Späth'sche Baumschulen Handel GmbH, Tel.: 639 00 30, Fax: 63 90 03 30",
    mail: "info@spaethsche-baumschulen.de",
    www: "www.spaethsche-Baumschulen.de",
    bemerkungen: "Gartenmarkt mit rd. 100 Ausstellern, Baumschulen-Raritäten, Tulpensortenschau, Musik- und Kinderprogramm, Eintritt 8 € (10 % Rabatt auf alle Pflanzen der Späth'schen Baumschulen), ermäßigt 5 € (Schüler, Studenten, Azubis bis 28 Jahre), Kinder bis 16 Jahre frei",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/spaether-fruehling_4_web_klein.jpg",
    copyright: "Daniela Incoronato",
    rss_titel: "Späth'er Frühling"
    },
    {
    id: "192",
    bezirk: "Marzahn-Hellersdorf",
    bezeichnung: "Flower Power - Blütentraum zum Muttertag in den Gärten der Welt",
    strasse: "Blumberger Damm 44",
    plz: "12685",
    von: "2022-05-08",
    bis: "2022-05-08",
    zeit: "",
    veranstalter: "Gärten der Welt/Grün Berlin GmbH, Blumberger Damm 44, 12685 Berlin, Tel.: 700 906-720",
    mail: "",
    www: "www.gaertenderwelt.de",
    bemerkungen: "",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/flowerpower-ole-bader.jpg",
    copyright: "Ole Bader",
    rss_titel: "Flower Power - Blütentraum zum Muttertag in den Gärten der Welt"
    },
    {
    id: "231",
    bezirk: "Charlottenburg-Wilmersdorf",
    bezeichnung: "Whisky deluxe",
    strasse: "Olympischer Platz 3",
    plz: "14053",
    von: "2022-05-13",
    bis: "2022-05-14",
    zeit: "Fr 16:00-22:00 Sa 14:00-22:00",
    veranstalter: "Whisky-Herbst GbR, Tel.: 525 11 08",
    mail: "info@whisky-deluxe.com",
    www: "www.whisky-deluxe.com",
    bemerkungen: "im Olympiastadion Berlin, Einzelkarte Freitag oder Samstag an der Tageskasse und im Vorverkauf 20 €, Kombikarte für beide Tage an der Tageskasse 35 €, Kombikarte für beide Tage im Vorverkauf 30 €",
    bild: "",
    copyright: "",
    rss_titel: "Whisky deluxe"
    },
    {
    id: "285",
    bezirk: "Neukölln",
    bezeichnung: "Silent Concert am Rhododendronhain",
    strasse: "Buckower Damm 170",
    plz: "12349",
    von: "2022-05-14",
    bis: "2022-05-14",
    zeit: "16:30-20:00",
    veranstalter: "Grün Berlin GmbH",
    mail: "service@gruen-berlin.de",
    www: "gruen-berlin.de/",
    bemerkungen: "Mit Teresa Bergman: Kopfhörer-Konzert mit Live-Musik",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/heny-schulz.jpg",
    copyright: "Heny Schulz",
    rss_titel: "Silent Concert am Rhododendronhain"
    },
    {
    id: "138",
    bezirk: "Mitte",
    bezeichnung: "KoRo Frauenlauf Berlin",
    strasse: "Straße des 17. Juni",
    plz: "10557",
    von: "2022-05-14",
    bis: "2022-05-14",
    zeit: "14:00",
    veranstalter: "SCC Events GmbH, Tel.: 30 12 88 10, Fax: 30 12 88 20",
    mail: "",
    www: "www.berliner-frauenlauf.de",
    bemerkungen: "Start Straße des 17. Juni Höhe Große Querallee",
    bild: "",
    copyright: "",
    rss_titel: "KoRo Frauenlauf Berlin"
    },
    {
    id: "288",
    bezirk: "Neukölln",
    bezeichnung: "Sonntagskult am See: Tapula Rasa- Das Steptanz-Event!",
    strasse: "Sangershauser Weg 1",
    plz: "12349",
    von: "2022-05-15",
    bis: "2022-05-15",
    zeit: "14:00-18:00",
    veranstalter: "Grün Berlin GmbH",
    mail: "service@gruen-berlin.de",
    www: "gruen-berlin.de/",
    bemerkungen: "Festplatzbühne am See",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/steptanz.jpg",
    copyright: "Grün Berlin GmbH",
    rss_titel: "Sonntagskult am See: Tapula Rasa – Das Steptanz-Event!"
    },
    {
    id: "291",
    bezirk: "Neukölln",
    bezeichnung: "Bezauberndes Feenfest",
    strasse: "Sangershauser Weg 1",
    plz: "12349",
    von: "2022-05-22",
    bis: "2022-05-22",
    zeit: "14:00-18:00",
    veranstalter: "Grün Berlin GmbH",
    mail: "service@gruen-berlin.de",
    www: "gruen-berlin.de/",
    bemerkungen: "am Rhododendronhain",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/britzer-garten-feenfest.jpg",
    copyright: "Konstantin Boerner",
    rss_titel: "Bezauberndes Feenfest"
    },
    {
    id: "162",
    bezirk: "Spandau",
    bezeichnung: "Staakener Kinder- und Volksfest",
    strasse: "Ungewitterweg",
    plz: "13591",
    von: "2022-05-25",
    bis: "2022-05-29",
    zeit: "",
    veranstalter: "Schaustellerbetrieb Wollenschlaeger, Tel.: 03322/428 82 45, Fax: 03322/423 41 39, Mobil 0163/5000 600",
    mail: "info@wollenschlaeger-berlin.de",
    www: "www.wollenschlaeger-berlin.de",
    bemerkungen: "",
    bild: "",
    copyright: "",
    rss_titel: "Staakener Kinder- und Volksfest"
    },
    {
    id: "42",
    bezirk: "Treptow-Köpenick",
    bezeichnung: "Biermarkt Das Bierfestival auf Tour an der Späth'schen Baumschule",
    strasse: "Späthstraße",
    plz: "12437",
    von: "2022-05-26",
    bis: "2022-05-29",
    zeit: "",
    veranstalter: "Jüttner Entertainment, Tel.: 88 70 80 81, 88 70 80 82, Fax: 66 70 30 03, Mobil 0152/33 90 83 98",
    mail: "info@juettner-entertainment.de",
    www: "www.juettner-entertainment.de",
    bemerkungen: "Ecke Ligusterweg",
    bild: "",
    copyright: "",
    rss_titel: "Biermarkt Das Bierfestival auf Tour an der Späth'schen Baumschule"
    },
    {
    id: "111",
    bezirk: "Steglitz-Zehlendorf",
    bezeichnung: "68. Steglitzer Woche",
    strasse: "Bäkepark",
    plz: "12207",
    von: "2022-05-26",
    bis: "2022-06-12",
    zeit: "Mo-Do, So & Feiertage 14:00-22:00 Fr-Sa bis 23:00",
    veranstalter: "Schaustellerverband Berlin e. V., Tel.: 213 32 90, Fax: 213 40 34",
    mail: "info@svbev.de",
    www: "http://www.volksfest-berlin.de",
    bemerkungen: "Festpark am Teltowkanal, zwischen Hindenburgdamm und Ostpreußendamm, Eintritt frei",
    bild: "",
    copyright: "",
    rss_titel: "68. Steglitzer Woche"
    },
    {
    id: "30",
    bezirk: "Treptow-Köpenick",
    bezeichnung: "Müggelheimer Angerfest",
    strasse: "Alt-Müggelheim 22",
    plz: "12559",
    von: "2022-06-03",
    bis: "2022-06-06",
    zeit: "",
    veranstalter: "Jüttner Entertainment, Tel.: 88 70 80 81, 88 70 80 82, Fax: 66 70 30 03, Mobil 0152/33 90 83 98",
    mail: "info@juettner-entertainment.de",
    www: "www.juettner-entertainment.de",
    bemerkungen: "Eintritt frei, Bühnenprogramm, Street Food, Kunsthandwerk, Kinderfahrgeschäfte",
    bild: "",
    copyright: "",
    rss_titel: "Müggelheimer Angerfest"
    },
    {
    id: "294",
    bezirk: "Neukölln",
    bezeichnung: "Rendezvous im Garten – Tage der Parks und Gärten 2022",
    strasse: "Sangershauser Weg 1",
    plz: "12349",
    von: "2022-06-03",
    bis: "2022-06-05",
    zeit: "ganztägig",
    veranstalter: "Grün Berlin GmbH",
    mail: "service@gruen-berlin.de",
    www: "gruen-berlin.de/",
    bemerkungen: "Britzer Garten",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/britzer_garten_events_rendezvous_im_garten_plakat_2022.jpg",
    copyright: "Grün Berlin GmbH",
    rss_titel: "Rendezvous im Garten – Tage der Parks und Gärten 2022"
    },
    {
    id: "234",
    bezirk: "Tempelhof-Schöneberg",
    bezeichnung: "Biermarkt Trabrennbahn Mariendorf",
    strasse: "Hirzerweg 64",
    plz: "12107",
    von: "2022-06-03",
    bis: "2022-06-06",
    zeit: "",
    veranstalter: "Jüttner Entertainment, Tel.: 88 70 80 81, 88 70 80 82, Fax: 66 70 30 03, Mobil 0152/33 90 83 98",
    mail: "info@juettner-entertainment.de",
    www: "www.juettner-entertainment.de",
    bemerkungen: "Eintritt 2 €",
    bild: "",
    copyright: "",
    rss_titel: "Biermarkt Trabrennbahn Mariendorf"
    },
    {
    id: "21",
    bezirk: "Neukölln",
    bezeichnung: "Historische Hoffest Schloss Britz",
    strasse: "Alt-Britz 73",
    plz: "12359",
    von: "2022-06-04",
    bis: "2022-06-06",
    zeit: "Sa, So 10:00-22:00 Mo 10:00-19:00",
    veranstalter: "Carnica Historische Feste & Märkte, Tel.: 0171/515 32 70, Fax: 033602/55 40 26",
    mail: "post@carnica.de",
    www: "www.carnica-spectaculi.de",
    bemerkungen: "Kinder bis 5 Jahre und Ritter in Vollrüstung frei, Erwachsene 10 €, Schüler, Studenten & Gewandete 8 €, Knder 6 - 16 Jahre 4 €, Familie 25 € (2 Erwachsene mit allen eigenen Kindern/Enkeln bis 16 Jahre)",
    bild: "",
    copyright: "",
    rss_titel: "Historische Hoffest Schloss Britz"
    },
    {
    id: "222",
    bezirk: "Spandau",
    bezeichnung: "12. Run of Spirit - die inklusive Laufveranstaltung im Evangelischen Johannesstift",
    strasse: "Schönwalder Allee 26",
    plz: "13587",
    von: "2022-06-06",
    bis: "2022-06-06",
    zeit: "",
    veranstalter: "Evangelisches Johannesstift, Schönwalder Allee 26, 13587 Berlin, Tel.: 336 09 - 0",
    mail: "events@jsd.de",
    www: "www.run-of-spirit.de",
    bemerkungen: "",
    bild: "",
    copyright: "",
    rss_titel: "12. Run of Spirit - die inklusive Laufveranstaltung im Evangelischen Johannesstift"
    },
    {
    id: "84",
    bezirk: "Charlottenburg-Wilmersdorf",
    bezeichnung: "Berliner Kunstallee",
    strasse: "Schloßstraße 1",
    plz: "14059",
    von: "2022-06-11",
    bis: "2022-06-12",
    zeit: "11:00-18:00",
    veranstalter: "Cornelja Hasler, KUNSTHAND-BERLIN, Tel.: 40 63 70 31",
    mail: "info@kunsthand-berlin.de",
    www: "www.kunsthand-berlin.de",
    bemerkungen: "Schloßstr. 1 u.a., Mittelstreifen, vis-à-vis Schloss Charlottenburg, Eintritt frei",
    bild: "",
    copyright: "",
    rss_titel: "Berliner Kunstallee"
    },
    {
    id: "213",
    bezirk: "Mitte",
    bezeichnung: "27. UMWELTFESTIVAL der GRÜNEN LIGA Berlin",
    strasse: "Vor dem Brandenburger Tor",
    plz: "10117",
    von: "2022-06-12",
    bis: "2022-06-12",
    zeit: "11:00-19:00",
    veranstalter: "GRÜNE LIGA Berlin e. V. Prenzlauer Allee 8, 10405 Berlin, Tel.: 443 39 10",
    mail: "info@umweltfestival.de",
    www: "www.umweltfestival.de",
    bemerkungen: "",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/umweltfestival600.jpg",
    copyright: "Sebastian Hennigs",
    rss_titel: "27. UMWELTFESTIVAL der GRÜNEN LIGA Berlin"
    },
    {
    id: "144",
    bezirk: "Mitte",
    bezeichnung: "Berliner Wasserbetriebe 5x5 km TEAM-Staffel",
    strasse: "Scheidemannstraße",
    plz: "10557",
    von: "2022-06-15",
    bis: "2022-06-17",
    zeit: "18:00",
    veranstalter: "SCC Events GmbH, Tel.: 30 12 88 10, Fax: 30 12 88 20",
    mail: "",
    www: "www.berliner-teamstaffel.de",
    bemerkungen: "Start: nördl. Tiergarten, zwischen Bundeskanzleramt und Scheidemannstraße",
    bild: "",
    copyright: "",
    rss_titel: "Berliner Wasserbetriebe 5x5 km TEAM-Staffel"
    },
    {
    id: "141",
    bezirk: "Mitte",
    bezeichnung: "GERMAN MANAGEMENT RUN",
    strasse: "Scheidemannstraße",
    plz: "10557",
    von: "2022-06-16",
    bis: "2022-06-16",
    zeit: "18:00",
    veranstalter: "SCC Events GmbH, Tel.: 30 12 88 10, Fax: 30 12 88 20",
    mail: "",
    www: "https://managementrun.de/run/",
    bemerkungen: "Start: nördl. Tiergarten, zwischen Bundeskanzleramt und Scheidemannstraße",
    bild: "",
    copyright: "",
    rss_titel: "GERMAN MANAGEMENT RUN"
    },
    {
    id: "33",
    bezirk: "Treptow-Köpenick",
    bezeichnung: "Köpenicker Sommer",
    strasse: "Alt-Köpenick",
    plz: "12555",
    von: "2022-06-17",
    bis: "2022-06-19",
    zeit: "",
    veranstalter: "Jüttner Entertainment, Tel.: 88 70 80 81, 88 70 80 82, Fax: 66 70 30 03, Mobil 0152/33 90 83 98",
    mail: "info@juettner-entertainment.de",
    www: "www.juettner-entertainment.de",
    bemerkungen: "Eintritt frei, Bühnenprogramm, Street Food, Kunsthandwerk, Kinderfahrgeschäfte",
    bild: "",
    copyright: "",
    rss_titel: "Köpenicker Sommer"
    },
    {
    id: "105",
    bezirk: "Mitte",
    bezeichnung: "59. Berliner Volksfestsommer auf dem Zentralen Festplatz",
    strasse: "Kurt-Schumacher-Damm 207",
    plz: "13405",
    von: "2022-06-17",
    bis: "2022-07-31",
    zeit: "Mi-Sa ab 14:00 So ab 13:00",
    veranstalter: "Schaustellerverband Berlin e. V., Tel.: 213 32 90, Fax: 213 40 34",
    mail: "info@svbev.de",
    www: "http://www.volksfest-berlin.de",
    bemerkungen: "Mo, Di geschlossen, Eintritt frei, www.svbev.de",
    bild: "",
    copyright: "",
    rss_titel: "59. Berliner Volksfestsommer auf dem Zentralen Festplatz"
    },
    {
    id: "189",
    bezirk: "Charlottenburg-Wilmersdorf",
    bezeichnung: "Classic Days",
    strasse: "Kurfürstendamm",
    plz: "10789",
    von: "2022-06-18",
    bis: "2022-06-19",
    zeit: "10:00",
    veranstalter: "PeReCi-Motor-Klassic Club e. V., Tel. und Fax: 742 22 37",
    mail: "info@pereci.de",
    www: "www.pereci.de",
    bemerkungen: "Sa 10:00-21:00, So 10:00-20:00",
    bild: "",
    copyright: "",
    rss_titel: "Classic Days"
    },
    {
    id: "297",
    bezirk: "Neukölln",
    bezeichnung: "SonntagsKult am See: Songslam",
    strasse: "Sangershauser Weg 1",
    plz: "12349",
    von: "2022-06-19",
    bis: "2022-06-19",
    zeit: "17:00-20:00",
    veranstalter: "Grün Berlin GmbH",
    mail: "service@gruen-berlin.de",
    www: "gruen-berlin.de/",
    bemerkungen: "Festplatzbühne am See",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/britzergarten_2022_songslam.jpg",
    copyright: "Konstantin Boerner",
    rss_titel: "SonntagsKult am See: Songslam"
    },
    {
    id: "300",
    bezirk: "Neukölln",
    bezeichnung: "DIVAS - Die Show",
    strasse: "Sangershauser Weg 1",
    plz: "12349",
    von: "2022-06-24",
    bis: "2022-06-24",
    zeit: "18:00",
    veranstalter: "Grün Berlin GmbH",
    mail: "service@gruen-berlin.de",
    www: "gruen-berlin.de/",
    bemerkungen: "",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/divas_show.jpg",
    copyright: "Stars in Concert",
    rss_titel: "DIVAS - Die Show"
    },
    {
    id: "309",
    bezirk: "Charlottenburg-Wilmersdorf",
    bezeichnung: "12. Familiensportfest im Olympiapark Berlin",
    strasse: "",
    plz: "",
    von: "2022-06-25",
    bis: "2022-06-26",
    zeit: "10:00-17:00",
    veranstalter: "Landessportbund Berlin e. V., Tel.: 30 00 21 18 oder 30 00 21 19",
    mail: "",
    www: "www.familiensportfest-berlin.de",
    bemerkungen: "Eintritt frei, Eingänge: Olympischer Platz, Hanns-Braun-Straße, Glockenturm",
    bild: "",
    copyright: "",
    rss_titel: "12. Familiensportfest im Olympiapark Berlin"
    },
    {
    id: "207",
    bezirk: "Mitte",
    bezeichnung: "9. KENAKO – Afrika Festival Berlin 2022",
    strasse: "Alexanderplatz",
    plz: "10178",
    von: "2022-06-30",
    bis: "2022-07-10",
    zeit: "Mo-Sa 10:00-22:00 So 10:00-20:00",
    veranstalter: "Afrika Medien Zentrum e. V. Großkopfstr. 6 - 7, 13403 Berlin",
    tel: "97 89 55 36",
    fax: "96 08 99 97",
    mail: "kenako@kenako-festival.de",
    www: "www.kenako-festival.de",
    bemerkungen: "Eintritt frei",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/lonam-das-afrikamagazin.jpg",
    copyright: "LoNam - Das Afrikamagazin",
    rss_titel: "9. KENAKO – Afrika Festival Berlin 2022"
    },
    {
    id: "78",
    bezirk: "Tempelhof-Schöneberg",
    bezeichnung: "37. Rocktreff & Spielfest",
    strasse: "Prühßstraße",
    plz: "12105",
    von: "2022-07-01",
    bis: "2022-07-03",
    zeit: "",
    veranstalter: "Catering Company GmbH, Herr Arzig, Tel.: 282 21 84, 0170/222 12 20, Fax: 28 59 81 40",
    mail: "cateringcompany@email.de",
    www: "www.catering-company-berlin.de",
    bemerkungen: "Volkspark Mariendorf, Newcomer-Bands stellen sich vor, Eintritt frei",
    bild: "",
    copyright: "",
    rss_titel: "37. Rocktreff & Spielfest"
    },
    {
    id: "165",
    bezirk: "Charlottenburg-Wilmersdorf",
    bezeichnung: "Drehorgelfest",
    strasse: "Breitscheidplatz",
    plz: "10789",
    von: "2022-07-01",
    bis: "2022-07-03",
    zeit: "",
    veranstalter: "Schaustellerbetrieb Wollenschlaeger, Tel.: 03322/428 82 45, Fax: 03322/423 41 39, Mobil 0163/5000 600",
    mail: "info@wollenschlaeger-berlin.de",
    www: "www.wollenschlaeger-berlin.de",
    bemerkungen: "an der Kaiser-Wilhelm-Gedächtniskirche, Kurfürstendamm",
    bild: "",
    copyright: "",
    rss_titel: "Drehorgelfest"
    },
    {
    id: "216",
    bezirk: "Friedrichshain-Kreuzberg",
    bezeichnung: "Kreuzberg-Festival",
    strasse: "Kreuzbergstraße",
    plz: "10178",
    von: "2022-07-01",
    bis: "2022-07-03",
    zeit: "Fr 16:00-23:00 Sa 11:00-23:00 So 11:00-20:00",
    veranstalter: "Kreuzberg-Festival e. V., Baruther Str. 1, 10961 Berlin, Tel.: 25 29 44 50",
    mail: "office@kreuzberg-festival.de",
    www: "http://kreuzberg-festival.de",
    bemerkungen: "",
    bild: "",
    copyright: "",
    rss_titel: "Kreuzberg-Festival"
    },
    {
    id: "255",
    bezirk: "Charlottenburg-Wilmersdorf",
    bezeichnung: "Kiezfest auf der Mierendorff-INSEL",
    strasse: "Mierendorffplatz",
    plz: "10589",
    von: "2022-07-01",
    bis: "2022-07-01",
    zeit: "16:00-21:00",
    veranstalter: "DorfwerkStadt e. V., Tel.: 344 58 74, Fax: 34 09 63 48",
    mail: "team@dorfwerkstadt.de",
    www: "www.dorfwerkstadt.de",
    bemerkungen: "",
    bild: "",
    copyright: "",
    rss_titel: "Kiezfest auf der Mierendorff-INSEL"
    },
    {
    id: "129",
    bezirk: "Mitte",
    bezeichnung: "VeloCity Berlin",
    strasse: "Straße des 17. Juni",
    plz: "10557",
    von: "2022-07-02",
    bis: "2022-07-03",
    zeit: "",
    veranstalter: "SCC Events GmbH, Tel.: 30 12 88 10, Fax: 30 12 88 20",
    mail: "",
    www: "https://velocity.berlin/",
    bemerkungen: "Start Straße des 17. Juni Höhe Große Querallee",
    bild: "",
    copyright: "",
    rss_titel: "VeloCity Berlin"
    },
    {
    id: "246",
    bezirk: "Charlottenburg-Wilmersdorf",
    bezeichnung: "KPM Hoffest",
    strasse: "Wegelystraße 1",
    plz: "10623",
    von: "2022-07-02",
    bis: "2022-07-03",
    zeit: "Sa 10:00-18:00 So 13:00-18:00",
    veranstalter: "KPM Königliche Porzellan-Manufaktur Berlin GmbH, Wegelystr. 1, 10623 Berlin, Tel.: 390 09 232",
    mail: "theresa.haala-hirt@kpm-berlin.com",
    www: "www.kpm-berlin.com",
    bemerkungen: "Kulinarisches Angebot, Kinderprogramm, Manufakturführungen und natürlich Porzellan",
    bild: "",
    copyright: "",
    rss_titel: "KPM Hoffest"
    },
    {
    id: "69",
    bezirk: "Reinickendorf",
    bezeichnung: "11. Tegeler Hafenfest",
    strasse: "Greenwichpromenade",
    plz: "13507",
    von: "2022-07-14",
    bis: "2022-07-17",
    zeit: "Do 15:00-22:00 Fr 14:00-23:00 Sa 10:00-23:00 So 10:00-20:00",
    veranstalter: "Catering Company GmbH, Herr Arzig, Tel.: 282 21 84, 0170/222 12 20, Fax: 28 59 81 40",
    mail: "cateringcompany@email.de",
    www: "www.catering-company-berlin.de",
    bemerkungen: "3 Bühnen, 2 Höhenfeuerwerke, Eintritt 7-14 Jahre Tageskarte 3 €, Dauerkarte 6 €, ab 15 Jahre Tageskarte 5 €, Dauerkarte 10 €, bis zum vollendeten 6. Lebensjahr Eintritt frei",
    bild: "",
    copyright: "",
    rss_titel: "11. Tegeler Hafenfest"
    },
    {
    id: "240",
    bezirk: "Treptow-Köpenick",
    bezeichnung: "Esskultur Markt Späth'sche Baumschulen",
    strasse: "Ligusterweg",
    plz: "12437",
    von: "2022-07-15",
    bis: "2022-07-17",
    zeit: "",
    veranstalter: "Jüttner Entertainment, Tel.: 88 70 80 81, 88 70 80 82, Fax: 66 70 30 03, Mobil 0152/33 90 83 98",
    mail: "info@juettner-entertainment.de",
    www: "www.juettner-entertainment.de",
    bemerkungen: "Eintritt 2 €",
    bild: "",
    copyright: "",
    rss_titel: "Esskultur Markt Späth'sche Baumschulen"
    },
    {
    id: "195",
    bezirk: "Marzahn-Hellersdorf",
    bezeichnung: "Berliner HighlandGames in den Gärten der Welt",
    strasse: "Blumberger Damm 44",
    plz: "12685",
    von: "2022-07-16",
    bis: "2022-07-17",
    zeit: "",
    veranstalter: "Gärten der Welt/Grün Berlin GmbH, Blumberger Damm 44, 12685 Berlin, Tel.: 700 906-720",
    mail: "",
    www: "www.gaertenderwelt.de",
    bemerkungen: "",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/highlandgames-frank-sperling.jpg",
    copyright: "Frank Sperling",
    rss_titel: "Berliner HighlandGames in den Gärten der Welt"
    },
    {
    id: "210",
    bezirk: "Mitte",
    bezeichnung: "Berlin lacht!",
    strasse: "Alexanderplatz",
    plz: "10178",
    von: "2022-07-16",
    bis: "2022-07-31",
    zeit: "11:00-22:00 Markt ab 13:00 Kulturprogramm",
    veranstalter: "Berlin lacht! e.V.",
    tel: "0177/612 77 72",
    mail: "stefanie.rosse@berlin-lacht.de",
    www: "www.berlin-lacht.de",
    bemerkungen: "",
    bild: "",
    copyright: "",
    rss_titel: "Berlin lacht!"
    },
    {
    id: "219",
    bezirk: "Tempelhof-Schöneberg",
    bezeichnung: "28. Lesbisch-schwules Stadtfest Berlin",
    strasse: "Motzstraße",
    plz: "10777",
    von: "2022-07-16",
    bis: "2022-07-17",
    zeit: "11:00",
    veranstalter: "Regenbogenfonds e. V., Fuggerstr. 7, 10777 Berlin, Tel.: 21 47 35 86, Fax: 21 47 35 88",
    mail: "info@stadtfest.berlin.de",
    www: "www.stadtfest.berlin.de",
    bemerkungen: "Motzstraße/Eisenacher Straße/Fuggerstraße/Kalckreuthstraße/Nollendorfplatz",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/motzblick600.jpg",
    copyright: "Brigitte Dummer",
    rss_titel: "28. Lesbisch-schwules Stadtfest Berlin"
    },
    {
    id: "114",
    bezirk: "Mitte",
    bezeichnung: "CSD Berlin Pride",
    strasse: "Leipziger Straße",
    plz: "10117",
    von: "2022-07-23",
    bis: "2022-07-23",
    zeit: "13:00",
    veranstalter: "Berliner CSD e. V., Tel.: 69 81 87 90",
    mail: "office@csd-berlin.de",
    www: "www.csd-berlin.de",
    bemerkungen: "Beginn zwischen Charlottenstraße und Axel-Springer-Straße, Ende der Demonstration auf der Straße des 17. Juni (zwischen Kl. Stern und Platz des 18. März), Abschlussveranstaltung dort 16:00 bis Mitternacht",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/berliner_csd_by_ninushkaphotography_500px.jpg",
    copyright: "ninushkaphotography",
    rss_titel: "CSD Berlin Pride"
    },
    {
    id: "45",
    bezirk: "Treptow-Köpenick",
    bezeichnung: "Biermarkt Das Bierfestival auf Tour Müggelheim",
    strasse: "Festwiese Müggelheimer Damm",
    plz: "12559",
    von: "2022-07-29",
    bis: "2022-07-31",
    zeit: "",
    veranstalter: "Jüttner Entertainment, Tel.: 88 70 80 81, 88 70 80 82, Fax: 66 70 30 03, Mobil 0152/33 90 83 98",
    mail: "info@juettner-entertainment.de",
    www: "www.juettner-entertainment.de",
    bemerkungen: "",
    bild: "",
    copyright: "",
    rss_titel: "Biermarkt Das Bierfestival auf Tour Müggelheim"
    },
    {
    id: "237",
    bezirk: "Tempelhof-Schöneberg",
    bezeichnung: "Esskultur Markt Trabrennbahn Mariendorf",
    strasse: "Hirzerweg 64",
    plz: "12107",
    von: "2022-07-29",
    bis: "2022-07-31",
    zeit: "",
    veranstalter: "Jüttner Entertainment, Tel.: 88 70 80 81, 88 70 80 82, Fax: 66 70 30 03, Mobil 0152/33 90 83 98",
    mail: "info@juettner-entertainment.de",
    www: "www.juettner-entertainment.de",
    bemerkungen: "Eintritt 2 €",
    bild: "",
    copyright: "",
    rss_titel: "Esskultur Markt Trabrennbahn Mariendorf"
    },
    {
    id: "243",
    bezirk: "Treptow-Köpenick",
    bezeichnung: "Biermarkt Berlin Müggelheim",
    strasse: "Festwiese Müggelheimer Damm",
    plz: "12559",
    von: "2022-07-29",
    bis: "2022-07-31",
    zeit: "",
    veranstalter: "Jüttner Entertainment, Tel.: 88 70 80 81, 88 70 80 82, Fax: 66 70 30 03, Mobil 0152/33 90 83 98",
    mail: "info@juettner-entertainment.de",
    www: "www.juettner-entertainment.de",
    bemerkungen: "Eintritt 2 €",
    bild: "",
    copyright: "",
    rss_titel: "Biermarkt Berlin Müggelheim"
    },
    {
    id: "132",
    bezirk: "Charlottenburg-Wilmersdorf",
    bezeichnung: "adidas Runners City Night Berlin 2022",
    strasse: "Kurfürstendamm",
    plz: "10789",
    von: "2022-07-30",
    bis: "2022-07-30",
    zeit: "19:00",
    veranstalter: "SCC Events GmbH, Tel.: 30 12 88 10, Fax: 30 12 88 20",
    mail: "",
    www: "www.berlin-citynight.de",
    bemerkungen: "Start und Ziel: Kurfürstendamm Nähe Kaiser-Wilhelm-Gedächtniskirche",
    bild: "",
    copyright: "",
    rss_titel: "adidas Runners City Night Berlin 2022"
    },
    {
    id: "48",
    bezirk: "Tempelhof-Schöneberg",
    bezeichnung: "Biermarkt Das Bierfestival auf Tour Tempelhof",
    strasse: "Sachsendamm 47",
    plz: "10829",
    von: "2022-08-05",
    bis: "2022-08-07",
    zeit: "",
    veranstalter: "Jüttner Entertainment, Tel.: 88 70 80 81, 88 70 80 82, Fax: 66 70 30 03, Mobil 0152/33 90 83 98",
    mail: "info@juettner-entertainment.de",
    www: "www.juettner-entertainment.de",
    bemerkungen: "Ikea Parkplatz",
    bild: "",
    copyright: "",
    rss_titel: "Biermarkt Das Bierfestival auf Tour Tempelhof"
    },
    {
    id: "279",
    bezirk: "Spandau",
    bezeichnung: "Spandauer Havelfest 2022",
    strasse: "Lindenufer",
    plz: "13597",
    von: "2022-08-12",
    bis: "2022-08-14",
    zeit: "Fr, Sa 11:00-23:00 So 11:00-20:00",
    veranstalter: "Partner für Spandau Gesellschaft für Bezirks-Marketing GmbH, Breite Str. 37, 13597 Berlin, Tel.: 36 75 72 61, Fax: 35 30 23 32",
    mail: "info@partner-fuer-spandau.de",
    www: "www.partner-fuer-spandau.de",
    bemerkungen: "",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/pfs_spandauer-havelfest.jpg",
    copyright: "Partner für Spandau",
    rss_titel: "Spandauer Havelfest 2022"
    },
    {
    id: "12",
    bezirk: "Friedrichshain-Kreuzberg",
    bezeichnung: "LesBiSchwules Parkfest",
    strasse: "Volkspark Friedrichshain",
    plz: "10249",
    von: "2022-08-13",
    bis: "2022-08-13",
    zeit: "15:00-21:45",
    veranstalter: "AWO Berlin Spree-Wuhle e. V., Tel.: 42 08 90 34, Fax: 42 08 92 99",
    mail: "info@parkfest-friedrichshain.de",
    www: "www.parkfest-friedrichshain.de",
    bemerkungen: "",
    bild: "",
    copyright: "",
    rss_titel: "LesBiSchwules Parkfest"
    },
    {
    id: "201",
    bezirk: "Marzahn-Hellersdorf",
    bezeichnung: "Culture meets Garden in den Gärten der Welt",
    strasse: "Blumberger Damm 44",
    plz: "12685",
    von: "2022-08-13",
    bis: "2022-08-14",
    zeit: "",
    veranstalter: "Gärten der Welt/Grün Berlin GmbH, Blumberger Damm 44, 12685 Berlin, Tel.: 700 906-720",
    mail: "",
    www: "www.gaertenderwelt.de",
    bemerkungen: "",
    bild: "",
    copyright: "",
    rss_titel: "Culture meets Garden in den Gärten der Welt"
    },
    {
    id: "6",
    bezirk: "Reinickendorf",
    bezeichnung: "119. Freie Scholle",
    strasse: "Waidmannsluster Damm 85",
    plz: "13469",
    von: "2022-08-19",
    bis: "2022-09-04",
    zeit: "15:00",
    veranstalter: "Schaustellerverband Berlin e. V., Tel.: 213 32 90 und 0172/300 68 73, Fax: 213 40 34",
    mail: "info@svbev.de",
    www: "http://www.volksfest-berlin.de",
    bemerkungen: "Eintritt frei, www.svbev.de",
    bild: "",
    copyright: "",
    rss_titel: "119. Freie Scholle"
    },
    {
    id: "270",
    bezirk: "Treptow-Köpenick",
    bezeichnung: "Köpenicker Winzersommer in der Altstadt Köpenick",
    strasse: "Schlossinsel",
    plz: "12557",
    von: "2022-08-19",
    bis: "2022-08-28",
    zeit: "Fr 14:00-22:00 Sa 11:00-22:00 So 11:00-20:00",
    veranstalter: "Laubinger Event GmbH, Tel.: 033439 7714 34 90, Fax: 033439/14 34 92",
    mail: "info@laubinger.de",
    www: "www.laubinger.de",
    bemerkungen: "Altstadt Köpenick, Eintritt frei, in Zusammenarbeit mit dem Altstadt Köpenick e. V.",
    bild: "",
    copyright: "",
    rss_titel: "Köpenicker Winzersommer in der Altstadt Köpenick"
    },
    {
    id: "72",
    bezirk: "Reinickendorf",
    bezeichnung: "90er Olymp",
    strasse: "Am Freibad 9",
    plz: "13469",
    von: "2022-08-19",
    bis: "2022-08-19",
    zeit: "16:00",
    veranstalter: "Catering Company GmbH, Herr Arzig, Tel.: 282 21 84, 0170/222 12 20, Fax: 28 59 81 40",
    mail: "cateringcompany@email.de",
    www: "www.catering-company-berlin.de",
    bemerkungen: "Strandbad Lübars, Einlass ab 16:00, Show 18:00-23:00, Eintritt ab 19,90 €",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/1908.jpg",
    copyright: "Catering Company GmbH",
    rss_titel: "90er Olymp"
    },
    {
    id: "303",
    bezirk: "Neukölln",
    bezeichnung: "Feuerblumen und Klassik Open-Air",
    strasse: "Sangershauser Weg 1",
    plz: "12349",
    von: "2022-08-20",
    bis: "2022-08-20",
    zeit: "19:30",
    veranstalter: "Grün Berlin GmbH",
    mail: "service@gruen-berlin.de",
    www: "gruen-berlin.de/",
    bemerkungen: "Berliner Symphoniker auf der offenen Bühne am See",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/feuerblumen-und-klassik-open-air-im-britzer-garten.jpg",
    copyright: "Lutz Griesbach",
    rss_titel: "Feuerblumen und Klassik Open-Air"
    },
    {
    id: "75",
    bezirk: "Reinickendorf",
    bezeichnung: "Schlagerolymp",
    strasse: "Am Freibad 9",
    plz: "13469",
    von: "2022-08-20",
    bis: "2022-08-20",
    zeit: "11:00",
    veranstalter: "Catering Company GmbH, Herr Arzig, Tel.: 282 21 84, 0170/222 12 20, Fax: 28 59 81 40",
    mail: "cateringcompany@email.de",
    www: "www.catering-company-berlin.de",
    bemerkungen: "Strandbad Lübars, Einlass ab 11:00, Show 13:00-23:00, Eintritt ab 44,90 €",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/so2022.jpg",
    copyright: "Catering Company GmbH",
    rss_titel: "Schlagerolymp"
    },
    {
    id: "126",
    bezirk: "Treptow-Köpenick",
    bezeichnung: "Töpferkunstmarkt",
    strasse: "Späthstraße 80/81",
    plz: "12437",
    von: "2022-08-20",
    bis: "2022-08-21",
    zeit: "10:00-18:00",
    veranstalter: "Späth'sche Baumschulen Handel GmbH, Tel.: 639 00 30, Fax: 63 90 03 30",
    mail: "info@spaethsche-baumschulen.de",
    www: "www.spaethsche-Baumschulen.de",
    bemerkungen: "mit rd. 40 hochkarätigen Töpfereien und Keramikmeistereien, Live-Musikprogramm und Töpfervorführungen, Eintritt 5 € (10 % Rabatt auf alle Pflanzen der Späth'schen Baumschulen), Kinder bis 16 Jahre frei",
    bild: "",
    copyright: "",
    rss_titel: "Töpferkunstmarkt"
    },
    {
    id: "177",
    bezirk: "Steglitz-Zehlendorf",
    bezeichnung: "Sommermarkt auf der Domäne Dahlem",
    strasse: "Königin-Luise-Straße 49",
    plz: "14195",
    von: "2022-08-20",
    bis: "2022-08-21",
    zeit: "",
    veranstalter: "Domäne Dahlem Veranstaltungsgesellschaft mbH, Königin-Luise-Str. 49, 14195 Berlin, Tel.: 66 63 00 19, Fax: 66 63 00 20",
    mail: "marktfeste@domaene-dahlem.de",
    www: "https://www.domaene-dahlem.de/marktfeste/",
    bemerkungen: "Eintritt regulär 3,50 €, ermäßigt 2 €, Kinder unter 12 frei",
    bild: "",
    copyright: "",
    rss_titel: "Sommermarkt auf der Domäne Dahlem"
    },
    {
    id: "252",
    bezirk: "Charlottenburg-Wilmersdorf",
    bezeichnung: "Kiezfest des Kiezbündnisses Klausenerplatz",
    strasse: "Klausenerplatz",
    plz: "14159",
    von: "2022-08-20",
    bis: "2022-08-20",
    zeit: "14:00-22:00",
    veranstalter: "Kiezbündnis Klausenerplatz e. V., Seelingstr. 14, 14059, Tel.: 308 244 955, Mobil 0171/17 53 17 33, Fax: 308 244 988",
    mail: "vorstand@klausenerplatz.de",
    www: "www.klausenerplatz.de",
    bemerkungen: "",
    bild: "",
    copyright: "",
    rss_titel: "Kiezfest des Kiezbündnisses Klausenerplatz"
    },
    {
    id: "117",
    bezirk: "Treptow-Köpenick",
    bezeichnung: "28. Internationales Müggelseeschwimmen",
    strasse: "Müggelschlößchenweg 70",
    plz: "12559",
    von: "2022-08-21",
    bis: "2022-08-21",
    zeit: "11:00",
    veranstalter: "TiB-Org.-Team, Tel.: 611 01 00",
    mail: "events@tib1848eV.de",
    www: "www.tib1848eV.de",
    bemerkungen: "Start: Seglergemeinschaft am Müggelsee, Ziel Strandbad Rahnsdorf",
    bild: "",
    copyright: "",
    rss_titel: "28. Internationales Müggelseeschwimmen"
    },
    
    {
    id: "306",
    bezirk: "Friedrichshain-Kreuzberg",
    bezeichnung: "radioeins Parkfest im Park am Gleisdreieck (Ostpark)",
    strasse: "",
    plz: "10963",
    von: "2022-08-27",
    bis: "2022-09-04",
    zeit: "",
    veranstalter: "radioeins vom RBB, Marlene-Dietrich-Allee 20, 14482 Potsdam, Tel.: 0331/7009 06 41",
    mail: "office@radioeins.de",
    www: "www.radioeins.de",
    bemerkungen: "",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/radioeinsparkfest2019.jpg",
    copyright: "radioeins",
    rss_titel: "radioeins Parkfest im Park am Gleisdreieck (Ostpark)"
    },
    {
    id: "198",
    bezirk: "Marzahn-Hellersdorf",
    bezeichnung: "Viva la musica - Filmmusik und Feuerwerk in der Arena der Gärten der Welt",
    strasse: "Blumberger Damm 44",
    plz: "12685",
    von: "2022-08-27",
    bis: "2022-08-27",
    zeit: "19:30-22:30",
    veranstalter: "Gärten der Welt/Grün Berlin GmbH, Blumberger Damm 44, 12685 Berlin, Tel.: 700 906-720",
    mail: "",
    www: "www.gaertenderwelt.de",
    bemerkungen: "",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/vivalamusica-lutz-griesbach.jpg",
    copyright: "Lutz Griesbach",
    rss_titel: "Viva la musica - Filmmusik und Feuerwerk in der Arena der Gärten der Welt"
    },
    {
    id: "249",
    bezirk: "Pankow",
    bezeichnung: "Zug der Liebe",
    strasse: "Mauerpark",
    plz: "10437",
    von: "2022-08-27",
    bis: "2022-08-27",
    zeit: "13:00",
    veranstalter: "Zug der Liebe e. V., Pfarrstr. 129, 10317 Berlin, Tel.: 0163/436 85 24",
    mail: "",
    www: "http://zugderliebe.org",
    bemerkungen: "",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/zug-der-liebe-2019-jens-schwan.jpg",
    copyright: "Jens Schwan",
    rss_titel: "Zug der Liebe"
    },
    {
    id: "93",
    bezirk: "Steglitz-Zehlendorf",
    bezeichnung: "KUNST trifft HANDWERK",
    strasse: "Mexikoplatz",
    plz: "14163",
    von: "2022-08-28",
    bis: "2022-08-28",
    zeit: "11:00-18:00",
    veranstalter: "Cornelja Hasler, KUNSTHAND-BERLIN, Tel.: 40 63 70 31",
    mail: "info@kunsthand-berlin.de",
    www: "www.kunsthand-berlin.de",
    bemerkungen: "Kunsthandwerkermarkt, ca. 100 Aussteller, Handelsware nicht zugelassen, Vorplatz S-Bahnhof Mexikoplatz, Bülowstr. 1 - 8, Beerenstr. 66, Eintritt frei",
    bild: "",
    copyright: "",
    rss_titel: "KUNST trifft HANDWERK"
    },
    {
    id: "282",
    bezirk: "Spandau",
    bezeichnung: "Spandauer WeinSommer",
    strasse: "Markt",
    plz: "13597",
    von: "2022-09-01",
    bis: "2022-09-04",
    zeit: "Fr, Sa 11:00-23:00 So 11:00-20:00",
    veranstalter: "Partner für Spandau Gesellschaft für Bezirks-Marketing GmbH, Breite Str. 37, 13597 Berlin, Tel.: 36 75 72 61, Fax: 35 30 23 32",
    mail: "info@partner-fuer-spandau.de",
    www: "www.partner-fuer-spandau.de",
    bemerkungen: "",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/pfs_weinsommer_spandau.jpg",
    copyright: "Partner für Spandau",
    rss_titel: "Spandauer WeinSommer"
    },
    {
    id: "3",
    bezirk: "Charlottenburg-Wilmersdorf",
    bezeichnung: "Antikmeile Suarezstraße",
    strasse: "Suarezstraße",
    plz: "14057",
    von: "2022-09-03",
    bis: "2022-09-03",
    zeit: "12:00-20:00",
    veranstalter: "Beste Sammelfreunde UG (haftungsbeschränkt), Michael Schrottmeyer, Tel.: 20 00 20 10",
    mail: "info@oldthing.de",
    www: "https://oldthing.de/Berliner-Flohmarkt/Antikes-und-Sammeln/Antikmeile-Suarezstrasse/",
    bemerkungen: "Suarezstraße zwischen Kantstraße und Kaiserdamm",
    bild: "",
    copyright: "",
    rss_titel: "Antikmeile Suarezstraße"
    },
    {
    id: "15",
    bezirk: "Tempelhof-Schöneberg",
    bezeichnung: "Nachbarschaftsfest am Rathaus Schöneberg",
    strasse: "John-F.-Kennedy-Platz",
    plz: "10825",
    von: "2022-09-03",
    bis: "2022-09-03",
    zeit: "12:00-19:00",
    veranstalter: "Bezirksamt Tempelhof-Schöneberg, Kontakt: Herr Gößmann und Frau Frömberg, Tel.: 90277-2310 und -3497",
    mail: "veranstaltungen-pressestelle@ba-ts.berlin.de",
    www: "",
    bemerkungen: "und Freiherr-vom-Stein-Straße, Eintritt frei, familienfreundliche Preise für Speisen und Getränke, viele Attraktionen und Spielstände gratis",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/nachbarschaftsfest600.jpg",
    copyright: "BA Tempelhof-Schöneberg",
    rss_titel: "Nachbarschaftsfest am Rathaus Schöneberg"
    },
    {
    id: "36",
    bezirk: "Neukölln",
    bezeichnung: "Rudower Herbstmeile",
    strasse: "Alt-Rudow",
    plz: "12555",
    von: "2022-09-03",
    bis: "2022-09-04",
    zeit: "",
    veranstalter: "Jüttner Entertainment, Tel.: 88 70 80 81, 88 70 80 82, Fax: 66 70 30 03, Mobil 0152/33 90 83 98",
    mail: "info@juettner-entertainment.de",
    www: "www.juettner-entertainment.de",
    bemerkungen: "Eintritt frei, Bühnenprogramm, Street Food, Kunsthandwerk, Kinderfahrgeschäfte",
    bild: "",
    copyright: "",
    rss_titel: "Rudower Herbstmeile"
    },
    {
    id: "312",
    bezirk: "Spandau",
    bezeichnung: "Flugplatzfest 2022 - Tag der Reservisten",
    strasse: "Am Flugplatz Gatow",
    plz: "14089",
    von: "2022-09-03",
    bis: "2022-09-04",
    zeit: "10:00-18:00",
    veranstalter: "Militärhistorisches Museum der Bundeswehr Flugplatz Berlin-Gatow, Tel.: 36 87 26 01",
    mail: "",
    www: "www.mhm-gatow.de",
    bemerkungen: "Anfahrt und Einlass über 'Am Flugplatz Gatow' (Museumseingang), Eintritt frei",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/flugplatzfest_2018_img_9381.jpg",
    copyright: "MHM Gatow",
    rss_titel: "Flugplatzfest 2022 - Tag der Reservisten"
    },
    {
    id: "81",
    bezirk: "Reinickendorf",
    bezeichnung: "12. Pyrotalia",
    strasse: "Am Freibad 9",
    plz: "13469",
    von: "2022-09-03",
    bis: "2022-09-03",
    zeit: "17:00-23:00",
    veranstalter: "Catering Company GmbH, Herr Arzig, Tel.: 282 21 84, 0170/222 12 20, Fax: 28 59 81 40",
    mail: "cateringcompany@email.de",
    www: "www.catering-company-berlin.de",
    bemerkungen: "Strandbad Lübars, Show mit Live-Band und 3 Feuerwerken, Eintritt ab 21,90 €",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/pyro.jpg",
    copyright: "Catering Company GmbH",
    rss_titel: "12. Pyrotalia"
    },
    {
    id: "87",
    bezirk: "Charlottenburg-Wilmersdorf",
    bezeichnung: "Berliner Kunstallee",
    strasse: "Schloßstraße 1",
    plz: "14059",
    von: "2022-09-03",
    bis: "2022-09-04",
    zeit: "11:00-18:00",
    veranstalter: "Cornelja Hasler, KUNSTHAND-BERLIN, Tel.: 40 63 70 31",
    mail: "info@kunsthand-berlin.de",
    www: "www.kunsthand-berlin.de",
    bemerkungen: "Schloßstr. 1 u.a., Mittelstreifen, vis-à-vis Schloss Charlottenburg, Eintritt frei",
    bild: "",
    copyright: "",
    rss_titel: "Berliner Kunstallee"
    },
    {
    id: "120",
    bezirk: "Friedrichshain-Kreuzberg",
    bezeichnung: "36. Kreuzberger Viertelmarathon",
    strasse: "Columbiadamm 111",
    plz: "10965",
    von: "2022-09-04",
    bis: "2022-09-04",
    zeit: "10:00",
    veranstalter: "TiB-Org.-Team, Tel.: 611 01 00",
    mail: "events@tib1848eV.de",
    www: "www.tib1848eV.de",
    bemerkungen: "Start und Ziel: TiB-Stadion",
    bild: "",
    copyright: "",
    rss_titel: "36. Kreuzberger Viertelmarathon"
    },
    {
    id: "66",
    bezirk: "Tempelhof-Schöneberg",
    bezeichnung: "35. Wein- und Winzerfest Lichtenrade",
    strasse: "Alt-Lichtenrade",
    plz: "12309",
    von: "2022-09-09",
    bis: "2022-09-11",
    zeit: "Fr 14:00-23:00 Sa 12:00-23:00 So 11:00-20:00",
    veranstalter: "Family & Friends e. V., Tel.: 305 55 21, Fax: 76 90 74 76",
    mail: "weinfest@family-and-friends-eV.de",
    www: "www.family-and-friends-eV.de",
    bemerkungen: "rund um den Dorfteich",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/weinwinzerfestjazzpolizei.jpg",
    copyright: "André Ballin (Family & Friends e. V.)",
    rss_titel: "35. Wein- und Winzerfest Lichtenrade"
    },
    {
    id: "108",
    bezirk: "Mitte",
    bezeichnung: "Berliner Herbstrummel auf dem Zentralen Festplatz",
    strasse: "Kurt-Schumacher-Damm 207",
    plz: "13405",
    von: "2022-09-09",
    bis: "2022-10-09",
    zeit: "Mi-Sa ab 15:00 So ab 13:00",
    veranstalter: "Schaustellerverband Berlin e. V., Tel.: 213 32 90, Fax: 213 40 34",
    mail: "info@svbev.de",
    www: "http://www.volksfest-berlin.de",
    bemerkungen: "Mo, Di geschlossen, 03.10. ab 13:00, Eintritt frei, www.sv-bev.de",
    bild: "",
    copyright: "",
    rss_titel: "Berliner Herbstrummel auf dem Zentralen Festplatz"
    },
    {
    id: "168",
    bezirk: "Tempelhof-Schöneberg",
    bezeichnung: "Siedlerfest Marienfelde",
    strasse: "Festplatz am Reinstedter Weg",
    plz: "12277",
    von: "2022-09-09",
    bis: "2022-09-11",
    zeit: "",
    veranstalter: "Schaustellerbetrieb Wollenschlaeger, Tel.: 03322/428 82 45, Fax: 03322/423 41 39, Mobil 0163/5000 600",
    mail: "info@wollenschlaeger-berlin.de",
    www: "www.wollenschlaeger-berlin.de",
    bemerkungen: "",
    bild: "",
    copyright: "",
    rss_titel: "Siedlerfest Marienfelde"
    },
    {
    id: "228",
    bezirk: "Tempelhof-Schöneberg",
    bezeichnung: "'Whisky-Herbst'",
    strasse: "Bessemerstraße 2 - 14",
    plz: "12103",
    von: "2022-09-09",
    bis: "2022-09-10",
    zeit: "Fr 15:00-22:00 Sa 13:00-22:00",
    veranstalter: "Whisky-Herbst GbR, Tel.: 525 11 08",
    mail: "info@whiskyherbst.de",
    www: "www.whisky-herbst.de",
    bemerkungen: "Malzfabrik Tempelhof, Eintritt",
    bild: "",
    copyright: "",
    rss_titel: "'Whisky-Herbst'"
    },
    {
    id: "267",
    bezirk: "Pankow",
    bezeichnung: "Rosenthaler Herbst in Berlin-Rosenthal",
    strasse: "Hauptstr. 155-171",
    plz: "13158",
    von: "2022-09-16",
    bis: "2022-09-18",
    zeit: "",
    veranstalter: "Laubinger Event GmbH, Tel.: 033439 7714 34 90, Fax: 033439/14 34 92",
    mail: "info@laubinger.de",
    www: "www.laubinger.de",
    bemerkungen: "traditionelles Erntedankfest mit Bühnenprogramm und großem Festumzug, Festbeitrag 1 €, Kinder bis 14 Jahre frei",
    bild: "",
    copyright: "",
    rss_titel: "Rosenthaler Herbst in Berlin-Rosenthal"
    },
    {
    id: "39",
    bezirk: "Treptow-Köpenick",
    bezeichnung: "Müggelheimer Erntefest",
    strasse: "Festwiese Müggelheim",
    plz: "12559",
    von: "2022-09-16",
    bis: "2022-09-18",
    zeit: "",
    veranstalter: "Jüttner Entertainment, Tel.: 88 70 80 81, 88 70 80 82, Fax: 66 70 30 03, Mobil 0152/33 90 83 98",
    mail: "info@juettner-entertainment.de",
    www: "www.juettner-entertainment.de",
    bemerkungen: "Eintritt 1 €, Bühnenprogramm, Street Food, Kunsthandwerk, Kinderfahrgeschäfte",
    bild: "",
    copyright: "",
    rss_titel: "Müggelheimer Erntefest"
    },
    {
    id: "171",
    bezirk: "Spandau",
    bezeichnung: "Oktoberfest Spandau",
    strasse: "Am Juliusturm",
    plz: "13599",
    von: "2022-09-16",
    bis: "2022-10-29",
    zeit: "",
    veranstalter: "Schaustellerbetrieb Wollenschlaeger, Tel.: 03322/428 82 45, Fax: 03322/423 41 39, Mobil 0163/5000 600",
    mail: "info@wollenschlaeger-berlin.de",
    www: "www.wollenschlaeger-berlin.de",
    bemerkungen: "Ecke Zitadellenweg",
    bild: "",
    copyright: "",
    rss_titel: "Oktoberfest Spandau"
    },
    {
    id: "60",
    bezirk: "Charlottenburg-Wilmersdorf",
    bezeichnung: "Herbstzauber in Westend",
    strasse: "Preußenallee",
    plz: "14052",
    von: "2022-09-17",
    bis: "2022-09-18",
    zeit: "Sa 12:00-23:00 So 12:00-20:00",
    veranstalter: "Family & Friends e. V., Tel.: 305 55 21, Fax: 76 90 74 76",
    mail: "stadtkultur@family-and-friends-eV.de",
    www: "www.family-and-friends.de",
    bemerkungen: "",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/hip-westend.jpg",
    copyright: "André Ballin (Family & Friends e. V.)",
    rss_titel: "Herbstzauber in Westend"
    },
    {
    id: "99",
    bezirk: "Reinickendorf",
    bezeichnung: "KUNST trifft HANDWERK Frohnau",
    strasse: "Zeltinger Platz",
    plz: "13465",
    von: "2022-09-17",
    bis: "2022-09-18",
    zeit: "11:00-18:00",
    veranstalter: "Cornelja Hasler, KUNSTHAND-BERLIN, Tel.: 40 63 70 31",
    mail: "info@kunsthand-berlin.de",
    www: "www.kunsthand-berlin.de",
    bemerkungen: "Kunsthandwerkermarkt, ca. 120 Aussteller, Handelsware nicht zugelassen, Zentrum der Gartenstadt Frohnau, Zeltinger Platz/Wiltinger Str. 1-26 oder Ludolfingerplatz, Eintritt frei",
    bild: "",
    copyright: "",
    rss_titel: "KUNST trifft HANDWERK Frohnau"
    },
    {
    id: "180",
    bezirk: "Steglitz-Zehlendorf",
    bezeichnung: "Kartoffelfest",
    strasse: "Königin-Luise-Straße 49",
    plz: "14195",
    von: "2022-09-17",
    bis: "2022-09-18",
    zeit: "",
    veranstalter: "Domäne Dahlem Veranstaltungsgesellschaft mbH, Königin-Luise-Str. 49, 14195 Berlin, Tel.: 66 63 00 19, Fax: 66 63 00 20",
    mail: "marktfeste@domaene-dahlem.de",
    www: "https://www.domaene-dahlem.de/marktfeste/",
    bemerkungen: "Eintritt regulär 3,50 €, ermäßigt 2 €, Kinder unter 12 frei",
    bild: "",
    copyright: "",
    rss_titel: "Kartoffelfest"
    },
    {
    id: "9",
    bezirk: "Treptow-Köpenick",
    bezeichnung: "Traditionsfest mit grünem Markt",
    strasse: "Späthstraße 80-81",
    plz: "12437",
    von: "2022-09-24",
    bis: "2022-09-25",
    zeit: "09:00-18:00",
    veranstalter: "Späth'sche Baumschulen Handel GmbH, Tel.: 639 00 30, Fax: 63 90 03 30",
    mail: "info@spaethsche-baumschulen.de",
    www: "http://www.spaethsche-baumschulen.de",
    bemerkungen: "Gartenmarkt und Kunsthandwerk mit 120 Ausstellern, Pflanzenausstellung, Apfelverkostung, Musik- und Kinderprogramm, Eintritt 8 € (10 % Rabatt auf alle Pflanzen der Späth'schen Baumschulen), ermäßigt 5 € (Schüler, Studierende, Azubis bis 28 Jahre), Kinder bis 16 Jahre frei",
    bild: "",
    copyright: "",
    rss_titel: "Traditionsfest mit grünem Markt"
    },
    {
    id: "147",
    bezirk: "Mitte",
    bezeichnung: "BMW BERLIN-MARATHON inlinescating 2022",
    strasse: "Potsdamer Platz",
    plz: "10117",
    von: "2022-09-24",
    bis: "2022-09-24",
    zeit: "15:30",
    veranstalter: "SCC Events GmbH, Tel.: 30 12 88 10, Fax: 30 12 88 20",
    mail: "",
    www: "www.scating.bmw-berlin-marathon.com",
    bemerkungen: "Start: Potsdamer Straße Höhe Potsdamer Platz",
    bild: "",
    copyright: "",
    rss_titel: "BMW BERLIN-MARATHON inlinescating 2022"
    },
    {
    id: "150",
    bezirk: "Mitte",
    bezeichnung: "Mini-MARATHON 2022",
    strasse: "Straße des 17. Juni",
    plz: "10557",
    von: "2022-09-24",
    bis: "2022-09-24",
    zeit: "15:10",
    veranstalter: "SCC Events GmbH, Tel.: 30 12 88 10, Fax: 30 12 88 20",
    mail: "schulen@scc-events.com",
    www: "https://www.bmw-berlin-marathon.com/juniors/mini-marathon/",
    bemerkungen: "Start: Straße des 17. Juni Höhe Bellevueallee/Bremer Weg (Kleiner Stern)",
    bild: "",
    copyright: "",
    rss_titel: "Mini-MARATHON 2022"
    },
    {
    id: "153",
    bezirk: "Mitte",
    bezeichnung: "BMW BERLIN-MARATHON 2022",
    strasse: "Straße des 17. Juni",
    plz: "10557",
    von: "2022-09-25",
    bis: "2022-09-25",
    zeit: "09:15",
    veranstalter: "SCC Events GmbH, Tel.: 30 12 88 10, Fax: 30 12 88 20",
    mail: "",
    www: "www.bmw-berlin-marathon.com",
    bemerkungen: "Start: Straße des 17. Juni Höhe Bellevueallee/Bremer Weg (Kleiner Stern)",
    bild: "",
    copyright: "",
    rss_titel: "BMW BERLIN-MARATHON 2022"
    },
    {
    id: "225",
    bezirk: "Spandau",
    bezeichnung: "Erntedankfest im Evangelischen Johannesstift",
    strasse: "Schönwalder Allee 26",
    plz: "13587",
    von: "2022-09-25",
    bis: "2022-09-25",
    zeit: "11:00-19:00",
    veranstalter: "Evangelisches Johannesstift, Schönwalder Allee 26, 13587 Berlin, Tel.: 336 09 - 0",
    mail: "events@jsd.de",
    www: "www.evangelisches-johannesstift.de",
    bemerkungen: "",
    bild: "",
    copyright: "",
    rss_titel: "Erntedankfest im Evangelischen Johannesstift"
    },
    {
    id: "264",
    bezirk: "Marzahn-Hellersdorf",
    bezeichnung: "Erntefest Hellersdorf",
    strasse: "Alice-Salomon-Platz",
    plz: "12627",
    von: "2022-10-01",
    bis: "2022-10-03",
    zeit: "Fr 12:00-22:00 Sa 10:00-23:00 So 10:00-20:00",
    veranstalter: "Laubinger Event GmbH, Tel.: 033439 7714 34 90, Fax: 033439/14 34 92",
    mail: "info@laubinger.de",
    www: "www.laubinger.de",
    bemerkungen: "geplant - Hellersdorfer Straße, großes Stadt- und Erntefest, Kirmes auf der Festmeile, Eintritt frei",
    bild: "",
    copyright: "",
    rss_titel: "Erntefest Hellersdorf"
    },
    {
    id: "276",
    bezirk: "Tempelhof-Schöneberg",
    bezeichnung: "Schöneberger Kürbisfest",
    strasse: "Akazienstraße",
    plz: "10823",
    von: "2022-10-01",
    bis: "2022-10-02",
    zeit: "Sa 11:00-20:00 So 10:00-20:00",
    veranstalter: "MS-Event-Agentur GmbH, Geschäftsführerin Frau Sieg-Heuke, Tel.: 0173/237 88 55",
    mail: "berlin@ms-event-agentur.com",
    www: "http://www.ms-event-agentur.com/",
    bemerkungen: "Akazien-/Belziger Straße, Eintritt frei",
    bild: "",
    copyright: "",
    rss_titel: "Schöneberger Kürbisfest"
    },
    {
    id: "24",
    bezirk: "Spandau",
    bezeichnung: "4. Gauklerfest auf der Zitadelle Spandau",
    strasse: "Am Juliusturm 65",
    plz: "13599",
    von: "2022-10-01",
    bis: "2022-10-03",
    zeit: "Sa, So 10:00-22:00  Mo 10:00-19:00",
    veranstalter: "Carnica Historische Feste & Märkte, Tel.: 0171/515 32 70, Fax: 033602/55 40 26",
    mail: "post@carnica.de",
    www: "www.carnica-spectaculi.de",
    bemerkungen: "Kinder bis 5 Jahre und Ritter in Vollrüstung frei, Erwachsene 12 €, Schüler, Studenten & Gewandete 9 €, Knder 6 - 16 Jahre 6 €, Familie 30 € (2 Erwachsene mit allen eigenen Kindern/Enkeln bis 16 Jahre)",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/gaukler500.jpg",
    copyright: "Carnica",
    rss_titel: "4. Gauklerfest auf der Zitadelle Spandau"
    },
    {
    id: "183",
    bezirk: "Steglitz-Zehlendorf",
    bezeichnung: "Erntefest auf der Domäne Dahlem",
    strasse: "Königin-Luise-Straße 49",
    plz: "14195",
    von: "2022-10-01",
    bis: "2022-10-02",
    zeit: "",
    veranstalter: "Domäne Dahlem Veranstaltungsgesellschaft mbH, Königin-Luise-Str. 49, 14195 Berlin, Tel.: 66 63 00 19, Fax: 66 63 00 20",
    mail: "marktfeste@domaene-dahlem.de",
    www: "https://www.domaene-dahlem.de/marktfeste/",
    bemerkungen: "Eintritt regulär 3,50 €, ermäßigt 2 €, Kinder unter 12 frei",
    bild: "",
    copyright: "",
    rss_titel: "Erntefest auf der Domäne Dahlem"
    },
    {
    id: "186",
    bezirk: "Steglitz-Zehlendorf",
    bezeichnung: "Herbstmarkt mit Textilien und Kunsthandwerk auf der Domäne Dahlem",
    strasse: "Königin-Luise-Straße 49",
    plz: "14195",
    von: "2022-10-29",
    bis: "2022-10-30",
    zeit: "",
    veranstalter: "Domäne Dahlem Veranstaltungsgesellschaft mbH, Königin-Luise-Str. 49, 14195 Berlin, Tel.: 66 63 00 19, Fax: 66 63 00 20",
    mail: "marktfeste@domaene-dahlem.de",
    www: "https://www.domaene-dahlem.de/marktfeste/",
    bemerkungen: "Eintritt regulär 3,50 €, ermäßigt 2 €, Kinder unter 12 frei",
    bild: "",
    copyright: "",
    rss_titel: "Herbstmarkt mit Textilien und Kunsthandwerk auf der Domäne Dahlem"
    },
    {
    id: "204",
    bezirk: "Marzahn-Hellersdorf",
    bezeichnung: "16. Kunst- und Keramikmarkt 2022",
    strasse: "Alt-Marzahn 19-23",
    plz: "12685",
    von: "2022-11-12",
    bis: "2022-11-13",
    zeit: "10:00-18:00",
    veranstalter: "KulturGut und „Schamottchen“ Alt-Marzahn 19/23, 12685 Berlin, Tel.: 56 29 42 83/86",
    mail: "petrich@agrar-boerse-ev.de",
    www: "",
    bemerkungen: "Live Vorführungen, Musik und kulinarische Angebote",
    bild: "/sen/web/service/maerkte-feste/strassen-volksfeste/assets/marktabends600.jpg",
    copyright: "Werner Petrich",
    rss_titel: "16. Kunst- und Keramikmarkt 2022"
    },
    {
    id: "135",
    bezirk: "Charlottenburg-Wilmersdorf",
    bezeichnung: "Berliner Silvesterlauf 2022",
    strasse: "Waldschulallee 34",
    plz: "14055",
    von: "2022-12-31",
    bis: "2022-12-31",
    zeit: "12:00",
    veranstalter: "SCC Events GmbH, Tel.: 30 12 88 10, Fax: 30 12 88 20",
    mail: "",
    www: "https://www.berliner-silvesterlauf.de/",
    bemerkungen: "Start vor dem Mommsenstadion",
    bild: "",
    copyright: "",
    rss_titel: "Berliner Silvesterlauf 2022"
    }
    ]
    
  

    export default data;